version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5435:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./packages/backend/data/postgres:/var/lib/postgresql/data
    env_file:
      - ./packages/backend/.env.production
    networks:
      - aqa

  pgadmin:
    restart: always
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - ./packages/backend/data/pgadmin:/var/lib/pgadmin
    env_file:
      - ./packages/backend/.env.production
    networks:
      - aqa

  backend:
    build:
      context: ./packages/backend
    restart: always
    container_name: backend
    image: sskorol/aqa-be:0.0.1
    ports:
      - "9090:9090"
    env_file:
      - ./packages/backend/.env.production
    networks:
      - aqa

  frontend:
    build:
      context: ./packages/frontend
      args:
        VITE_REACT_APP_BE_URL: "/api"
        VITE_REACT_APP_STRIPE_PUB_KEY: ""
    restart: always
    container_name: frontend
    image: sskorol/aqa-fe:0.0.1
    ports:
      - "3000:80"
    networks:
      - aqa

networks:
  aqa:
    driver: bridge
